//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4335.Windows.Zakharov_4335
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees
    {
        public string id_e { get; set; }
        public string role_e { get; set; }
        public string fio_e { get; set; }
        public string login_e { get; set; }
        public string password_e { get; set; }
        public string last_e { get; set; }
        public string type_e { get; set; }
    }
}
